<?php
$unix_time=xDiasAtras(2)['unix_time'];
$m=memcached();
$domainMD5=md5($domain);
$rank=ramRead($unix_time.'_domain_'.$domainMD5,$m);
if(!$rank){
	require '404.php';
}
$trend=upAndDown($domain,$m);
$data=[
	'assets'=>assetsDoSite(),
	'domain'=>$domain,
	'hits'=>123,
	'_include'=>[
		'inc/top'=>['_indent'=>5]
	],
	'language'=>linguagemDoSite(),
	'rank'=>$rank,
	'title'=>$domain,
	'trend'=>$trend
];
mustache('domain',$data);