<?php
$start=1;
$i=$start;
$pageLength=$_ENV['PAGE_LENGTH'];
$limit=$start+$pageLength;
$trends=null;
$unix_time=xDiasAtras(2)['unix_time'];
$m=memcached();
while($i<$limit){
	$domain=ramRead($unix_time.'_rank_'.$i,$m);
	$trends[]=[
		'domain'=>$domain,
		'rank'=>$i,
		'trend'=>upAndDown($domain,$m)
	];
	$i++;
}
$data=[
	'_include'=>[
		'inc/head'=>[
			'_indent'=>2,
			'headerAssets'=>assetsDoSite('header'),
			'title'=>$_ENV['SITE_NAME']
		],
		'inc/footer'=>[
			'footerAssets'=>assetsDoSite('footer')
		],
		'inc/nav'=>incNav(),
		'inc/trends'=>[
			'_indent'=>6,
			'trends'=>$trends,
			'nextPage'=>($pageLength+1)
		]
	],
	'language'=>linguagemDoSite(),
	'_Ranking de 1 milhão de sites'=>null
];
$data=i18n($data);
mustache('home',$data);