<?php
$start=1;
$i=$start;
$pageLength=$_ENV['PAGE_LENGTH'];
$limit=$start+$pageLength;
$trends=null;
$unix_time=xDiasAtras(2)['unix_time'];
while($i<$limit){
	$trends[]=[
		'domain'=>ramRead($unix_time.'_rank_'.$i),
		'rank'=>$i
	];
	$i++;
}
$data=[
	'assets'=>assetsDoSite(),
	'_include'=>[
		'inc/top'=>['_indent'=>5],
		'inc/trends'=>[
			'_indent'=>6,
			'trends'=>$trends,
			'nextPage'=>($pageLength+1)
		]
	],
	'language'=>linguagemDoSite(),
	'title'=>$_ENV['SITE_NAME']
];
mustache('index',$data);