<?php
if(!is_numeric($rank)){
	require '404.php';
}
$start=$rank;
$end=$start+$_ENV['PAGE_LENGTH'];
if($end<1000000){
	$nextPage=($end+1);
}else{
	$nextPage=false;
}
$trends=[];
$unix_time=xDiasAtras(2)['unix_time'];
$m=memcached();
while($start<=$end){
	$domain=ramRead($unix_time.'_rank_'.$start,$m);
	$trends[]=[
		'domain'=>$domain,
		'rank'=>$start,
		'trend'=>upAndDown($domain,$m)
	];
	$start++;
}
$data=[
	'_indent'=>6,
	'trends'=>$trends,
	'nextPage'=>$nextPage
];
mustache('inc/trends',$data);